/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* custom error messages */
#define CUSTOMERRORS "verrors.h"

/* Log Level */
/* #undef GLOB_LOG */

/* Warn Level */
/* #undef GLOB_SAFE */

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <fnmatch.h> header file. */
#define HAVE_FNMATCH_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `kios' library (-lkios). */
/* #undef HAVE_LIBKIOS */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you support file names longer than 14 characters. */
#define HAVE_LONG_FILE_NAMES 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Alpha processor */
/* #undef _ALPHA */

/* compiling as an Apache module */
/* #undef _APACHE_MODULE */

/* BeOS */
/* #undef _BEOS */

/* Big Endian System */
/* #undef _BIG_ENDIAN */

/* BSD */
/* #undef _BSD */

/* Debian Linux */
/* #undef _DEBIAN */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* FreeBSD */
/* #undef _FREEBSD */

/* enable GNU extensions */
#define _GNU_SOURCE 1

/* Intel */
#define _I386 1

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Linux */
#define _LINUX 1

/* Motorola 68k */
/* #undef _M68K */

/* MacOS X */
/* #undef _MACOSX */

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* NetBSD */
/* #undef _NETBSD */

/* OpenBSD */
/* #undef _OPENBSD */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */

/* Motorola PPC */
/* #undef _POWERPC */

/* RedHat Linux */
#define _REDHAT 1

/* Sun Solaris */
/* #undef _SOLARIS */

/* Sparc processor */
/* #undef _SPARC */

/* SuSE Linux */
/* #undef _SUSE */

/* Unix */
#define _UNIX 1

/* MS Windows */
/* #undef _WINDOWS */

/* Yellowdog Linux */
/* #undef _YELLOWDOG */
