// character properties.
{
U_nv,      U_numeric_value = U_nv,
U_bmg,     U_bidi_mirroring_glyph = U_bmg,
U_cf,      U_case_folding = U_cf,
U_dm,      U_decomposition_mapping = U_dm,
U_fc_nfkc, U_fc_nfkc_closure = U_fc_nfkc,
U_lc,      U_lowercase_mapping = U_lc,
U_scc,     U_special_case_condition = U_scc,
U_sfc,     U_simple_case_folding = U_sfc,
U_slc,     U_simple_lowercase_mapping = U_slc,
U_stc,     U_simple_titlecase_mapping = U_stc,
U_suc,     U_simple_uppercase_mapping = U_suc,
U_tc,      U_titlecase_mapping = U_tc,
U_uc,      U_uppercase_mapping = U_uc,
U_isc,     U_iso_comment = U_isc,
U_na,      U_name = U_na,
U_na1,     U_unicode_1_name = U_na1,
U_urs,     U_unicode_radical_stroke = U_urs,
U_age,
U_blk,     U_block = U_blk,
U_sc,      U_script = U_sc,
U_bc,      U_bidi_class = U_bc,
U_ccc,     U_canonical_combining_class = U_ccc,
U_dt,      U_decomposition_type = U_dt,
U_ea,      U_east_asian_width = U_ea,
U_gc,      U_general_category = U_gc,
U_gcb,     U_grapheme_cluster_break = U_gcb,
U_hst,     U_hangul_syllable_type = U_hst,
U_jg,      U_joining_group = U_jg,
U_jt,      U_joining_type = U_jt,
U_lb,      U_line_break = U_lb,
U_nfc_qc,  U_nfc_quick_check = U_nfc_qc,
U_nfd_qc,  U_nfd_quick_check = U_nfd_qc,
U_nfkc_qc, U_nfkc_quick_check = U_nfkc_qc,
U_nfkd_qc, U_nfkd_quick_check = U_nfkd_qc,
U_nt,      U_numeric_type = U_nt,
U_sb,      U_sentence_break = U_sb,
U_wb,      U_word_break = U_wb,
U_ahex,    U_ascii_hex_digit = U_ahex,
U_alpha,   U_alphabetic = U_alpha,
U_bidi_c,  U_bidi_control = U_bidi_c,
U_bidi_m,  U_bidi_mirrored = U_bidi_m,
U_ce,      U_composition_exclusion = U_ce,
U_comp_ex, U_full_composition_exclusion = U_comp_ex,
U_dash,
U_dep,     U_deprecated = U_dep,
U_di,      U_default_ignorable_code_point = U_di,
U_dia,     U_diacritic = U_dia,
U_ext,     U_extender = U_ext,
U_gr_base, U_grapheme_base = U_gr_base,
U_gr_ext,  U_grapheme_extend = U_gr_ext,
U_gr_link, U_grapheme_link = U_gr_link,
U_hex,     U_hex_digit = U_hex,
U_hyphen,
U_idc,     U_id_continue = U_idc,
U_ideo,    U_ideographic = U_ideo,
U_ids,     U_id_start = U_ids,
U_idsb,    U_ids_binary_operator = U_idsb,
U_idst,    U_ids_trinary_operator = U_idst,
U_join_c,  U_join_control = U_join_c,
U_loe,     U_logical_order_exception = U_loe,
U_lower,   U_lowercase = U_lower,
U_math,
U_nchar,   U_noncharacter_code_point = U_nchar,
U_oalpha,  U_other_alphabetic = U_oalpha,
U_odi,     U_other_default_ignorable_code_point = U_odi,
U_ogr_ext, U_other_grapheme_extend = U_ogr_ext,
U_oidc,    U_other_id_continue = U_oidc,
U_oids,    U_other_id_start = U_oids,
U_olower,  U_other_lowercase = U_olower,
U_omath,   U_other_math = U_omath,
U_oupper,  U_other_uppercase = U_oupper,
U_pat_syn, U_pattern_syntax = U_pat_syn,
U_pat_ws,  U_pattern_white_space = U_pat_ws,
U_qmark,   U_quotation_mark = U_qmark,
U_radical,
U_sd,      U_soft_dotted = U_sd,
U_sterm,
U_term,    U_terminal_punctuation = U_term,
U_uideo,   U_unified_ideograph = U_uideo,
U_upper,   U_uppercase = U_upper,
U_vs,      U_variation_selector = U_vs,
U_wspace,  U_white_space = U_wspace, U_space = U_wspace,
U_xidc,    U_xid_continue = U_xidc,
U_xids,    U_xid_start = U_xids,
U_xo_nfc,  U_expands_on_nfc = U_xo_nfc,
U_xo_nfd,  U_expands_on_nfd = U_xo_nfd,
U_xo_nfkc, U_expands_on_nfkc = U_xo_nfkc,
U_xo_nfkd, U_expands_on_nfkd = U_xo_nfkd
};
