// character property long names. matches enum.
{
"Numeric Value",
"Bidi Mirroring Glyph",
"Case Folding",
"Decomposition Mapping",
"FC NFKC Closure",
"Lowercase Mapping",
"Special Case Condition",
"Simple Case Folding",
"Simple Lowercase Mapping",
"Simple Titlecase Mapping",
"Simple Uppercase Mapping",
"Titlecase Mapping",
"Uppercase Mapping",
"ISO Comment",
"Name",
"Unicode 1 Name",
"Unicode Radical Stroke",
"Age",
"Block",
"Script",
"Bidi Class",
"Canonical Combining Class",
"Decomposition Type",
"East Asian Width",
"General Category",
"Grapheme Cluster Break",
"Hangul Syllable Type",
"Joining Group",
"Joining Type",
"Line Break",
"NFC Quick Check",
"NFD Quick Check",
"NFKC Quick Check",
"NFKD Quick Check",
"Numeric Type",
"Sentence Break",
"Word Break",
"ASCII Hex Digit",
"Alphabetic",
"Bidi Control",
"Bidi Mirrored",
"Composition Exclusion",
"Full Composition Exclusion",
"Dash",
"Deprecated",
"Default Ignorable Code Point",
"Diacritic",
"Extender",
"Grapheme Base",
"Grapheme Extend",
"Grapheme Link",
"Hex Digit",
"Hyphen",
"ID Continue",
"Ideographic",
"ID Start",
"IDS Binary Operator",
"IDS Trinary Operator",
"Join Control",
"Logical Order Exception",
"Lowercase",
"Math",
"Noncharacter Code Point",
"Other Alphabetic",
"Other Default Ignorable Code Point",
"Other Grapheme Extend",
"Other ID Continue",
"Other ID Start",
"Other Lowercase",
"Other Math",
"Other Uppercase",
"Pattern Syntax",
"Pattern White Space",
"Quotation Mark",
"Radical",
"Soft Dotted",
"STerm",
"Terminal Punctuation",
"Unified Ideograph",
"Uppercase",
"Variation Selector",
"White Space",
"XID Continue",
"XID Start",
"Expands On NFC",
"Expands On NFD",
"Expands On NFKC",
"Expands On NFKD"
};
